name: Android CI

on:
  push:
    branch:
      - master
      - patch-*
      - feature-*

  pull_request:
    branch:
      - master
      - patch-*
      - feature-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build
      run: gradle assembleDebug
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
        retention-days: 20
